- name: Modify README.md
  uses: jaywcjlove/github-action-modify-file-content@main
  with:
    path: adhifakhreza/agh/customfilter.txt
    body: "overwrite file content {{date:YYYY-MM-DD HH:mm:ss}}",
    overwrite: 'true'
